import {esc,safeUrl,dayOptions,busy,requireClient,koreaDay} from './ui.mjs?v=dcfc26fdbe14';import {updateRow,moveItems} from './sync.mjs?v=dcfc26fdbe14';
export function mountItinerary(root,client,state={}){
 let snapshot={itinerary:[]},date=koreaDay(),selected=new Set();const get=()=>requireClient(state.getClient?.()||client);const error=state.onError||alert;
 function render(s=snapshot,d=date){snapshot=s;date=d;const items=s.itinerary.filter(x=>x.date===date).sort((a,b)=>a.position-b.position||a.id.localeCompare(b.id));selected=new Set([...selected].filter(id=>s.itinerary.some(x=>x.id===id)));
 root.innerHTML=`<div class="trip-tools"><p><strong>${items.filter(x=>x.completed).length} / ${items.length}</strong> 已走過</p><div><label>移至 <select data-target>${dayOptions()}</select></label><button type="button" data-move>移動選取項目</button></div><small>「選取」用來移日期；「已完成」用來記錄去過。</small></div><ol class="timeline">${items.map(x=>`<li class="event ${x.completed?'completed':''}" data-id="${esc(x.id)}"><span class="event-time">${esc(x.time)}</span><article class="event-card"><div class="event-heading"><h3>${esc(x.title)}</h3>${x.badge?`<span class="badge">${esc(x.badge)}</span>`:''}<details class="event-options"><summary aria-label="操作 ${esc(x.title)}" title="行程操作">⋯</summary><div class="event-actions"><label><input type="checkbox" data-select ${selected.has(x.id)?'checked':''}> 選取</label><label><input type="checkbox" data-complete ${x.completed?'checked':''}> 已完成</label><button data-edit type="button">時間／備註</button><button data-order="up" type="button" aria-label="上移 ${esc(x.title)}">↑</button><button data-order="down" type="button" aria-label="下移 ${esc(x.title)}">↓</button></div></details></div>${x.original_date!==x.date?`<p class="original-note">原訂 ${esc(x.original_date)} · 請核對票券／預約</p>`:''}<p>${esc(x.detail)}</p>${x.address?`<p class="event-address">${esc(x.address)}</p>`:''}<div class="event-links">${x.url?`<a target="_blank" rel="noopener noreferrer" href="${esc(safeUrl(x.url))}">${x.type==='flight'?'查看航班動態':x.title==='豚笑 / 飯店旁醬蟹'?'醬蟹地圖':'開啟 Naver 地圖'} ↗</a>`:''}${(x.extra_links||[]).map(([url,label])=>`<a target="_blank" rel="noopener noreferrer" href="${esc(safeUrl(url))}">${esc(label)} ↗</a>`).join('')}${x.address?'<button type="button" data-copy-address>複製地址 ↗</button>':''}</div></article></li>`).join('')}</ol>${items.length?'':'<p class="empty">這天先留白，從其他天移入行程吧。</p>'}`;
 root.querySelector('[data-target]').value=date;
 root.querySelector('[data-move]').onclick=e=>busy(e.currentTarget,async()=>{const c=get(),ids=[...selected];if(!ids.length)throw Error('請先勾選要移動的行程');const target=root.querySelector('[data-target]').value;const moving=snapshot.itinerary.filter(x=>selected.has(x.id));if(moving.some(x=>x.badge||x.type==='flight')&&!confirm('選取項目包含票券、預約或航班。改行程日期不會改訂位，仍要移動嗎？'))return;await moveItems(c,ids,target,Object.fromEntries(moving.map(x=>[x.id,x.version])));selected.clear();state.onDay?.(target)},error);
 root.querySelectorAll('[data-id]').forEach(li=>{const row=items.find(x=>x.id===li.dataset.id);const options=li.querySelector('.event-options');options.ontoggle=()=>{if(options.open)root.querySelectorAll('.event-options[open]').forEach(other=>{if(other!==options)other.open=false})};const copy=li.querySelector('[data-copy-address]');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(row.address);state.onSaved?.('地址已複製')}catch{error('無法自動複製，請長按韓文地址複製')}};li.querySelector('[data-select]').onchange=e=>e.target.checked?selected.add(row.id):selected.delete(row.id);li.querySelector('[data-complete]').onchange=async e=>{const checkbox=e.target;checkbox.disabled=true;try{await updateRow(get(),'itinerary_items',row.id,{completed:checkbox.checked},row.version)}catch(e){checkbox.checked=row.completed;error(e.message)}finally{checkbox.disabled=false}};
 li.querySelector('[data-edit]').onclick=e=>busy(e.currentTarget,async()=>{const c=get();const time=prompt('行程時間（原有預約請核對）',row.time);if(time===null)return;const detail=prompt('備註',row.detail);if(detail===null)return;await updateRow(c,'itinerary_items',row.id,{time,detail},row.version)},error);
 li.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>busy(b,async()=>{const c=get(),i=items.indexOf(row),up=b.dataset.order==='up',neighbor=items[i+(up?-1:1)];if(!neighbor)return;const far=items[i+(up?-2:2)];const position=up?(far?(far.position+neighbor.position)/2:neighbor.position-1):(far?(far.position+neighbor.position)/2:neighbor.position+1);await updateRow(c,'itinerary_items',row.id,{position},row.version)},error));});
 }
 return {render};
}
