import {validateExpense,validateRates,summarize,format,convert} from './money.mjs?v=c2d3fef3332e';import {saveExpense,updateRow,deleteRow} from './sync.mjs?v=c2d3fef3332e';import {uploadPhoto,photoUrl,recognizePhoto,removePhoto} from './photos.mjs?v=c2d3fef3332e';import {esc,currencies,busy,requireClient,koreaDay,showPhotoViewer,duringRecognition} from './ui.mjs?v=c2d3fef3332e';
export function mountLedger(root,client,state={}){
 let snapshot={trip:{rates:null},expenses:[],photos:[]},draftId=crypto.randomUUID(),editVersion=null,attachment=null,requestId=null,receiptBlob=null,attachmentOwned=false,ratesDirty=false,ratesVersion=null;
 const get=()=>requireClient(state.getClient?.()||client),error=state.onError||alert;
 root.innerHTML=`<div class="wallet-toolbar"><button data-new class="accent-button">＋ 新增支出</button><button data-export>匯出 CSV</button><label>日期 <select data-day-filter><option value="all">全旅程</option></select></label></div><div data-ledger-summary class="wallet-summary"></div><details class="rate-card"><summary>共同換算匯率 · 手動設定</summary><p>填你們實際換匯／結算匯率，新支出會保存當時匯率。</p><form data-rates class="form-grid"><label>1 韓幣 = 台幣<input name="twdPerKrw" inputmode="decimal" placeholder="例：0.024" required></label><label>1 韓幣 = 澳門幣<input name="mopPerKrw" inputmode="decimal" placeholder="例：0.006" required></label><button class="accent-button">保存匯率</button><button type="button" data-reset-rates>載入最新匯率</button></form></details><form data-expense class="paper-form" hidden><div class="form-title"><h3 data-form-title>新增支出</h3><button data-cancel type="button">取消</button></div><div class="photo-actions"><label class="upload-button">📸 拍收據<input type="file" name="receipt" accept="image/jpeg,image/png,image/webp" capture="environment"></label><label class="upload-button">🖼 從相簿／檔案選取<input type="file" name="receiptAlbum" accept="image/jpeg,image/png,image/webp"></label><button type="button" data-recognize>自動辨識／重試</button><button type="button" data-detach>移除照片</button></div><div class="saved-photo-picker"><label>選取已存的共用照片<select data-existing-receipt><option value="">選擇照片</option></select></label><button type="button" data-use-existing-receipt>使用這張照片</button></div><p class="form-hint" data-ocr-status>免綁卡本機辨識；照片仍會保存並同步。首次載入較久，請核對後再記帳。</p><img data-receipt-preview class="receipt-preview" alt="待核對收據" hidden><details data-ocr-text hidden><summary>辨識原文</summary><pre></pre></details><div class="form-grid"><label>日期<input type="date" name="date" required></label><label>品項／店名<input name="title" maxlength="200" required></label><label>金額<input name="amount" inputmode="decimal" required></label><label>原始幣別<select name="currency">${currencies()}</select></label><label>誰先付款？<select name="payer"><option value="米">米</option><option value="凌">凌</option></select></label><label>怎麼分？<select name="split"><option value="equal">兩人均攤</option><option value="custom">各自金額</option><option value="mi">米個人</option><option value="ling">凌個人</option></select></label><label data-custom hidden>米應付<input name="mi" inputmode="decimal" value="0"></label><label data-custom hidden>凌應付<input name="ling" inputmode="decimal" value="0"></label></div><label class="wide-field">備註<textarea name="notes" rows="2"></textarea></label><label data-old-rate hidden><input type="checkbox" name="applyCurrentRates"> 舊支出改用目前匯率（未勾選保留舊匯率）</label><p data-preview class="conversion-preview"></p><button type="submit" class="accent-button">確認記帳</button><p class="form-hint">同一筆只能選一位付款人；兩人分別付款請拆成兩筆。</p></form><div data-expenses class="expense-list"></div><details class="photo-library"><summary>照片與未完成草稿 · 清理附件</summary><p>未確認支出不計入帳本；刪除照片會同步影響所有訪客。</p><div data-photos></div></details>`;
 const form=root.querySelector('[data-expense]'),ratesForm=root.querySelector('[data-rates]'),filter=root.querySelector('[data-day-filter]');let oldRates=null;
 const field=n=>form.elements.namedItem(n);
 const photoInUse=id=>snapshot.expenses.some(x=>x.receipt_id===id)||snapshot.menus?.some(x=>x.photo_id===id);
 root.querySelector('[data-use-existing-receipt]').onclick=e=>busy(e.currentTarget,async()=>{const photo=snapshot.photos.find(p=>p.id===root.querySelector('[data-existing-receipt]').value);if(!photo)throw Error('請先選一張已存照片');await showPhoto(photo);const previous=attachment,previousOwned=attachmentOwned;attachment=photo;attachmentOwned=false;receiptBlob=null;requestId=null;if(previousOwned&&previous&&previous.id!==photo.id&&!photoInUse(previous.id))await removePhoto(get(),previous);root.querySelector('[data-ocr-status]').textContent='已載入共用照片；按「自動辨識／重試」辨識金額，或直接手動填寫。'},error);
 function reset(){form.reset();field('date').value=koreaDay();draftId=crypto.randomUUID();editVersion=null;oldRates=null;attachment=null;requestId=null;receiptBlob=null;attachmentOwned=false;root.querySelector('[data-receipt-preview]').hidden=true;root.querySelector('[data-ocr-text]').hidden=true;root.querySelector('[data-ocr-status]').textContent='免綁卡本機辨識；照片仍會保存並同步。首次載入較久，請核對後再記帳。';root.querySelector('[data-form-title]').textContent='新增支出';root.querySelector('[data-old-rate]').hidden=true;preview()}
 function rates(){return editVersion&&!field('applyCurrentRates').checked?oldRates:snapshot.trip.rates}
 function preview(){root.querySelectorAll('[data-custom]').forEach(x=>x.hidden=field('split').value!=='custom');const dest=root.querySelector('[data-preview]');try{const original=field('amount').value||'0';const r=rates();dest.textContent=['KRW','TWD','MOP'].map(c=>format(convert(original,field('currency').value,c,r),c)).join(' · ')}catch{dest.textContent='填入金額並設定匯率後，會顯示三幣試算。'}}
 form.oninput=preview;form.onchange=preview;
 root.querySelector('[data-new]').onclick=()=>{if(!form.hidden&&!confirm('已有未儲存內容，要重新新增嗎？'))return;reset();form.hidden=false;field('title').focus()};
 root.querySelector('[data-cancel]').onclick=e=>busy(e.currentTarget,async()=>{if(attachmentOwned&&attachment&&!photoInUse(attachment.id)){await removePhoto(get(),attachment)}reset();form.hidden=true},error);
 root.querySelector('[data-detach]').onclick=e=>busy(e.currentTarget,async()=>{if(!attachment)return;if(attachmentOwned&&!photoInUse(attachment.id))await removePhoto(get(),attachment);attachment=null;requestId=null;receiptBlob=null;attachmentOwned=false;root.querySelector('[data-receipt-preview]').hidden=true;field('receipt').value=''},error);
 async function showPhoto(photo){const img=root.querySelector('[data-receipt-preview]');img.src=await photoUrl(get(),photo);img.hidden=false;}
 async function recognize(){if(!attachment)throw Error('請先拍照或選收據');const status=root.querySelector('[data-ocr-status]');const r=await duringRecognition(root,()=>recognizePhoto(get(),{photoId:attachment.id,mode:'receipt',blob:receiptBlob,onProgress:message=>status.textContent=message}));if(r.merchant)field('title').value=r.merchant;if(r.date)field('date').value=r.date;else root.querySelector('[data-ocr-status]').textContent='日期未辨識，請核對目前選擇的日期。';if(r.amountCandidates?.length){field('amount').value=r.amountCandidates[0].amount;field('currency').value='KRW'}const notice=r.uncertain?'金額有多個候選或未找到，請對照原圖手動核對。':'已辨識草稿，請核對店名、日期及總額。';root.querySelector('[data-ocr-status]').textContent=notice+(r.amountCandidates?.length?` 候選：${r.amountCandidates.map(x=>x.amount).join(' / ')} 韓幣`:'');root.querySelector('[data-ocr-text]').hidden=false;root.querySelector('[data-ocr-text] pre').textContent=r.text;preview()}
 async function selectReceipt(e){const f=e.target.files[0];if(!f)return;const btn=root.querySelector('[data-recognize]');await busy(btn,async()=>{const previous=attachment,previousOwned=attachmentOwned;const replacement=await uploadPhoto(get(),f,'receipt');attachment=replacement;attachmentOwned=true;receiptBlob=replacement.blob;requestId=crypto.randomUUID();if(previousOwned&&previous&&!photoInUse(previous.id)){try{await removePhoto(get(),previous)}catch(e){error(e.message+'；新照片已保存，舊照片可在附件區清理。')}}await showPhoto(attachment);try{await recognize()}catch(e){root.querySelector('[data-ocr-status]').textContent=e.message+'；照片已保存，可手動填寫。';error(e.message)}},error)}
 field('receipt').onchange=selectReceipt;field('receiptAlbum').onchange=selectReceipt;
 root.querySelector('[data-recognize]').onclick=e=>busy(e.currentTarget,async()=>{requestId=crypto.randomUUID();await recognize()},error);
 form.onsubmit=e=>{e.preventDefault();busy(form.querySelector('[type=submit]'),async()=>{const c=get(),data=Object.fromEntries(new FormData(form));const expense=validateExpense({...data,id:draftId,rates:rates(),shares:{mi:data.mi,ling:data.ling},receipt_id:attachment?.id||null});if(editVersion)expense.version=editVersion;await saveExpense(c,expense);reset();form.hidden=true;state.onSaved?.('已記帳')},error)};
 ratesForm.oninput=()=>{ratesDirty=true};
 root.querySelector('[data-reset-rates]').onclick=()=>{ratesDirty=false;ratesVersion=snapshot.trip.version;for(const key of ['twdPerKrw','mopPerKrw'])ratesForm.elements.namedItem(key).value=snapshot.trip.rates?.[key]||'';};
 ratesForm.onsubmit=e=>{e.preventDefault();busy(ratesForm.querySelector('button'),async()=>{const r=validateRates(Object.fromEntries(new FormData(ratesForm)));await updateRow(get(),'trips',snapshot.trip.id,{rates:r},ratesVersion??snapshot.trip.version);ratesDirty=false;ratesVersion=snapshot.trip.version;for(const key of ['twdPerKrw','mopPerKrw'])ratesForm.elements.namedItem(key).value=r[key];state.onSaved?.('匯率已保存')},error)};
 filter.onchange=()=>render(snapshot);
 root.querySelector('[data-export]').onclick=()=>{const rows=[['日期','品項','幣別','原幣金額','付款人','米應付','凌應付','分攤方式','台幣每韓幣','澳門幣每韓幣','備註'],...snapshot.expenses.map(x=>[x.date,x.title,x.currency,x.amount_minor/(x.currency==='KRW'?1:100),x.payer,x.mi_share_minor/(x.currency==='KRW'?1:100),x.ling_share_minor/(x.currency==='KRW'?1:100),x.split,x.rates.twdPerKrw,x.rates.mopPerKrw,x.notes])];const csv='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='釜山支出.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 function render(s){snapshot=s;const current=filter.value;const dates=[...new Set(s.expenses.map(x=>x.date))].sort();filter.innerHTML='<option value="all">全旅程</option>'+dates.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');filter.value=dates.includes(current)?current:'all';const entries=s.expenses.filter(x=>filter.value==='all'||x.date===filter.value),summary=summarize(entries,s.trip.rates),settle=summary.settlement;
 root.querySelector('[data-ledger-summary]').innerHTML=`<div class="total-card"><span>${filter.value==='all'?'全旅程':'當日'}總花費</span><strong>${format(summary.totals.KRW,'KRW')}</strong><p>${format(summary.totals.TWD,'TWD')} · ${format(summary.totals.MOP,'MOP')}</p></div><div class="settlement-card"><span>代付抵銷後</span><strong>${settle.from?`${settle.from} 補給 ${settle.to} ${format(settle.krw,'KRW')}`:'目前已結清'}</strong><p>${format(settle.TWD,'TWD')} · ${format(settle.MOP,'MOP')}</p><small>參考結算使用目前匯率；支出統計使用各筆匯率。</small></div><div class="paid-table"><p>米：已付 ${format(summary.paid['米'],'KRW')} ／應付 ${format(summary.owed['米'],'KRW')}</p><p>凌：已付 ${format(summary.paid['凌'],'KRW')} ／應付 ${format(summary.owed['凌'],'KRW')}</p></div>`;
 if(!ratesDirty&&!ratesForm.contains(document.activeElement)){ratesVersion=s.trip.version;for(const key of ['twdPerKrw','mopPerKrw'])ratesForm.elements.namedItem(key).value=s.trip.rates?.[key]||'';}
 root.querySelector('[data-expenses]').innerHTML=entries.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(x=>`<article class="expense-card" data-expense-id="${esc(x.id)}"><div><small>${esc(x.date)} · ${esc(x.payer)}先付</small><h3>${esc(x.title)}</h3><strong>${format(x.amount_minor/(x.currency==='KRW'?1:100),x.currency)}</strong><p>${['KRW','TWD','MOP'].map(c=>format(convert(x.amount_minor/(x.currency==='KRW'?1:100),x.currency,c,x.rates),c)).join(' · ')}</p><p>米 ${format(x.mi_share_minor/(x.currency==='KRW'?1:100),x.currency)} ／ 凌 ${format(x.ling_share_minor/(x.currency==='KRW'?1:100),x.currency)}</p>${x.notes?`<p>${esc(x.notes)}</p>`:''}</div><div class="expense-buttons"><button data-edit-expense>編輯</button>${x.receipt_id?'<button data-view-receipt>看收據</button>':''}<button data-delete-expense>刪除</button></div></article>`).join('')||'<p class="empty">還沒有支出，第一筆從拍收據開始。</p>';
 root.querySelectorAll('[data-expense-id]').forEach(el=>{const x=entries.find(x=>x.id===el.dataset.expenseId);el.querySelector('[data-edit-expense]').onclick=()=>{if(!form.hidden&&!confirm('放棄目前草稿，編輯這筆支出？'))return;reset();form.hidden=false;draftId=x.id;editVersion=x.version;oldRates=x.rates;for(const n of ['date','title','currency','payer','notes'])field(n).value=x[n]||'';field('amount').value=x.amount_minor/(x.currency==='KRW'?1:100);field('split').value=x.split||'custom';field('mi').value=x.mi_share_minor/(x.currency==='KRW'?1:100);field('ling').value=x.ling_share_minor/(x.currency==='KRW'?1:100);root.querySelector('[data-old-rate]').hidden=false;root.querySelector('[data-form-title]').textContent='編輯支出';attachment=s.photos.find(p=>p.id===x.receipt_id)||null;if(attachment)showPhoto(attachment).catch(e=>error(e.message));preview();form.scrollIntoView?.({behavior:'smooth',block:'center'})};el.querySelector('[data-delete-expense]').onclick=e=>busy(e.currentTarget,async()=>{if(!confirm('刪除這筆支出及收據？所有人帳本都會更新。'))return;await deleteRow(get(),'expenses',x);const photo=s.photos.find(p=>p.id===x.receipt_id);if(photo&&!s.expenses.some(other=>other.id!==x.id&&other.receipt_id===photo.id)&&!s.menus?.some(m=>m.photo_id===photo.id))await removePhoto(get(),photo)},error);if(x.receipt_id)el.querySelector('[data-view-receipt]').onclick=e=>busy(e.currentTarget,async()=>{const photo=s.photos.find(p=>p.id===x.receipt_id);if(!photo)throw Error('收據已被移除');const url=await photoUrl(get(),photo);showPhotoViewer(url)},error)});
 const photos=s.photos||[];const picker=root.querySelector('[data-existing-receipt]'),chosen=picker.value;picker.innerHTML='<option value="">選擇已存照片</option>'+photos.map(p=>`<option value="${esc(p.id)}">${p.kind==='menu'?'菜單':'收據'} · ${esc(p.id.slice(0,8))}</option>`).join('');picker.value=chosen;root.querySelector('[data-photos]').innerHTML=photos.map(p=>`<div class="photo-row" data-photo-id="${esc(p.id)}"><span>${p.kind==='menu'?'菜單':'收據'} · ${esc(p.id.slice(0,8))}</span><button data-see>查看</button><button data-remove>刪除照片</button></div>`).join('')||'<p>目前沒有照片。</p>';
 root.querySelectorAll('[data-photo-id]').forEach(el=>{const p=photos.find(p=>p.id===el.dataset.photoId);el.querySelector('[data-see]').onclick=e=>busy(e.currentTarget,async()=>showPhotoViewer(await photoUrl(get(),p)),error);el.querySelector('[data-remove]').onclick=e=>busy(e.currentTarget,async()=>{if(s.expenses.some(x=>x.receipt_id===p.id)||s.menus?.some(x=>x.photo_id===p.id))throw Error('照片仍被支出或菜單使用，請先移除對應附件／記錄');if(confirm('刪除這張未使用的照片？'))await removePhoto(get(),p)},error)});preview();
 }
 function setDraft(d){reset();form.hidden=false;for(const n of ['date','title','amount','currency','notes','payer','split'])if(d[n]!==undefined)field(n).value=d[n];preview()}
 reset();return {render,setDraft,getDraftId:()=>draftId};
}
