import {estimateMeal,format,toMinor} from './money.mjs?v=f6228d036dd9';import {saveMenu,deleteRow} from './sync.mjs?v=f6228d036dd9';import {uploadPhoto,photoUrl,recognizePhoto,removePhoto} from './photos.mjs?v=f6228d036dd9';import {esc,currencies,busy,requireClient,koreaDay} from './ui.mjs?v=f6228d036dd9';
export function mountMenu(root,client,state={},onExpenseDraft=()=>{}){
 let snapshot={trip:{rates:null},menus:[],photos:[]},draft={id:crypto.randomUUID(),title:'本餐試算',date:koreaDay(),items:[],budget:null,photo_id:null},dirty=false,requestId=null;
 const get=()=>requireClient(state.getClient?.()||client),error=state.onError||alert;
 root.innerHTML=`<div class="menu-saved"><select data-saved aria-label="保存的菜單"><option value="">選擇已保存菜單</option></select><button data-load>載入</button><button data-fresh>新增試算</button><button data-delete-menu>刪除這份</button></div><div class="paper-form"><div class="photo-actions"><label class="upload-button">📸 拍整張菜單<input data-menu-photo type="file" accept="image/jpeg,image/png,image/webp" capture="environment"></label><button data-menu-ocr>重新辨識／翻譯</button><button data-remove-menu-photo>移除菜單照片</button></div><p class="form-hint" data-menu-status>價格請先核對並勾「已確認」，再選菜色；小字／多欄菜單可分區拍攝。</p><img data-menu-preview class="menu-preview" alt="菜單原圖" hidden><div class="form-grid"><label>這份試算名稱<input data-menu-title maxlength="200" value="本餐試算"></label><label>用餐日期<input data-menu-date type="date"></label></div><div data-menu-items></div><button data-add-item>＋ 手動新增菜色／費用</button><div class="menu-tools"><label>整餐預算<input data-budget inputmode="decimal" placeholder="空白不判斷超支"></label><label>預算幣別<select data-budget-currency>${currencies()}</select></label><button data-save-menu class="accent-button">保存並同步試算</button></div><div data-menu-results class="menu-results" aria-live="polite"></div><button data-to-expense>帶入記帳草稿 →</button><p class="form-hint">預估價不含未填寫的服務費與額外費用；實際結帳後再核對。試算不會直接計入帳本。</p><details data-menu-text hidden><summary>菜單辨識原文</summary><pre></pre></details></div>`;
 const q=selector=>root.querySelector(selector);
 function touch(){dirty=true;q('[data-save-menu]').textContent='保存並同步試算';}
 function result(){try{const r=estimateMeal(draft.items,draft.budget,snapshot.trip.rates);q('[data-menu-results]').classList.toggle('budget-over',r.budgetState==='over');q('[data-menu-results]').innerHTML=`<span>這餐預估</span><strong>${format(r.totals.KRW,'KRW')}</strong><p>${format(r.totals.TWD,'TWD')} · ${format(r.totals.MOP,'MOP')}</p><p>${r.budgetState==='none'?'填入預算後可比較':r.budgetState==='exact'?'剛好達到預算':`${r.budgetState==='over'?'超出預算':'還剩預算'} ${format(Math.abs(r.difference),'KRW')}`}</p>`;return r}catch(e){q('[data-menu-results]').textContent=e.message;return null}}
 function draw(){q('[data-menu-title]').value=draft.title||'本餐試算';q('[data-menu-date]').value=draft.date||koreaDay();q('[data-budget]').value=draft.budget?.amount??'';q('[data-budget-currency]').value=draft.budget?.currency||'KRW';q('[data-menu-items]').innerHTML=draft.items.map((x,i)=>`<div class="menu-row ${x.selected?'selected':''}" data-item="${i}"><input data-select-item type="checkbox" aria-label="選取 ${esc(x.original_name)}" ${x.selected?'checked':''} ${x.confirmed&&x.price_minor>0?'':'disabled'}><div class="item-names"><label><small>韓文／原菜名</small><input data-name value="${esc(x.original_name)}"></label><label><small>繁體中文（可修正）</small><input data-translation value="${esc(x.translated_name)}" placeholder="翻譯／中文備註"></label><label><small>規格／份量</small><input data-spec value="${esc(x.spec)}" placeholder="大小份、重量、套餐"></label></div><div class="item-price"><label><small>單價 ₩</small><input data-price inputmode="numeric" value="${esc(x.price_minor??'')}" placeholder="待核對"></label><label><small>份數</small><input data-quantity type="number" min="1" max="100" value="${esc(x.quantity)}"></label><small data-price-conversion></small><label class="confirm-price"><input data-confirm type="checkbox" ${x.confirmed?'checked':''}> 價格已確認</label><button data-delete-item>移除此項</button></div></div>`).join('');
 q('[data-menu-items]').querySelectorAll('[data-item]').forEach(row=>{const x=draft.items[Number(row.dataset.item)];const select=row.querySelector('[data-select-item]');const price=row.querySelector('[data-price]');const updateConversion=()=>{const r=estimateMeal(x.price_minor>0?[{...x,confirmed:true,selected:true,quantity:1}]:[],null,snapshot.trip.rates);row.querySelector('[data-price-conversion]').textContent=`${format(r.totals.TWD,'TWD')} · ${format(r.totals.MOP,'MOP')}`};updateConversion();select.onchange=()=>{x.selected=select.checked;row.classList.toggle('selected',x.selected);touch();result()};for(const [attr,key] of [['data-name','original_name'],['data-translation','translated_name'],['data-spec','spec']])row.querySelector(`[${attr}]`).oninput=e=>{x[key]=e.target.value;touch()};price.oninput=()=>{try{x.price_minor=toMinor(price.value,'KRW')}catch{x.price_minor=null}x.confirmed=false;row.querySelector('[data-confirm]').checked=false;select.disabled=true;touch();updateConversion();result()};row.querySelector('[data-confirm]').onchange=e=>{if(e.target.checked&&!(x.price_minor>0)){e.target.checked=false;error('請先填有效韓幣價格');return}x.confirmed=e.target.checked;select.disabled=!x.confirmed;if(!x.confirmed){x.selected=false;select.checked=false;row.classList.remove('selected')}touch();result()};row.querySelector('[data-quantity]').oninput=e=>{x.quantity=Number(e.target.value);touch();result()};row.querySelector('[data-delete-item]').onclick=()=>{draft.items.splice(Number(row.dataset.item),1);touch();draw()}});result();}
 for(const selector of ['[data-menu-title]','[data-menu-date]','[data-budget]','[data-budget-currency]'])q(selector).oninput=()=>{draft.title=q('[data-menu-title]').value;draft.date=q('[data-menu-date]').value;draft.budget=q('[data-budget]').value===''?null:{amount:q('[data-budget]').value,currency:q('[data-budget-currency]').value};touch();result()};
 q('[data-add-item]').onclick=()=>{draft.items.push({id:crypto.randomUUID(),original_name:'',translated_name:'',spec:'',price_minor:null,quantity:1,confirmed:false,selected:false});touch();draw()};
 function fresh(){draft={id:crypto.randomUUID(),title:'本餐試算',date:koreaDay(),items:[],budget:null,photo_id:null};requestId=null;dirty=false;q('[data-menu-preview]').hidden=true;q('[data-menu-text]').hidden=true;draw()}
 q('[data-fresh]').onclick=()=>{if(dirty&&!confirm('目前尚未儲存，要開新試算嗎？'))return;fresh()};
 async function showPhoto(photo){q('[data-menu-preview]').src=await photoUrl(get(),photo);q('[data-menu-preview]').hidden=false}
 q('[data-remove-menu-photo]').onclick=e=>busy(e.currentTarget,async()=>{if(!draft.photo_id)return;const p=snapshot.photos.find(p=>p.id===draft.photo_id);if(p&&!snapshot.menus.some(x=>x.photo_id===p.id))await removePhoto(get(),p);draft.photo_id=null;q('[data-menu-preview]').hidden=true;touch()},error);
 async function recognize(){if(!draft.photo_id)throw Error('請先拍菜單');const r=await recognizePhoto(get(),{photoId:draft.photo_id,mode:'menu',requestId:requestId||=crypto.randomUUID()});draft.items=r.items;touch();draw();q('[data-menu-status]').textContent=r.translationWarning||'已辨識韓文與中文。請對照原圖核對品項、規格與價格，再勾選。';q('[data-menu-text]').hidden=false;q('[data-menu-text] pre').textContent=r.text}
 q('[data-menu-photo]').onchange=()=>{const f=q('[data-menu-photo]').files[0];if(!f)return;busy(q('[data-menu-ocr]'),async()=>{const photo=await uploadPhoto(get(),f,'menu');draft.photo_id=photo.id;touch();requestId=crypto.randomUUID();await showPhoto(photo);try{await recognize()}catch(e){q('[data-menu-status]').textContent=e.message+'；仍可手動新增。';error(e.message)}},error)};
 q('[data-menu-ocr]').onclick=e=>busy(e.currentTarget,async()=>{if(draft.items.length&&!confirm('重新辨識會取代這份菜單的品項與修改，要繼續嗎？'))return;requestId=crypto.randomUUID();await recognize()},error);
 q('[data-save-menu]').onclick=e=>busy(e.currentTarget,async()=>{if(!draft.title.trim())throw Error('請填試算名稱');if(!result())throw Error('請先修正試算資料');const r=await saveMenu(get(),draft);draft.version=r.version;dirty=false;state.onSaved?.('菜單試算已同步')},error);
 q('[data-load]').onclick=async()=>{const m=snapshot.menus.find(x=>x.id===q('[data-saved]').value);if(!m)return;if(dirty&&!confirm('放棄尚未保存的修改並載入？'))return;draft=structuredClone(m);dirty=false;requestId=null;q('[data-menu-preview]').hidden=true;draw();const p=snapshot.photos.find(p=>p.id===m.photo_id);if(p)showPhoto(p).catch(e=>error(e.message))};
 q('[data-delete-menu]').onclick=e=>busy(e.currentTarget,async()=>{const m=snapshot.menus.find(x=>x.id===draft.id);if(!m)throw Error('這份還未保存，可按新增試算清空');if(!confirm('刪除這份共用菜單試算？'))return;await deleteRow(get(),'menu_estimates',m);const p=snapshot.photos.find(p=>p.id===m.photo_id);if(p&&!snapshot.menus.some(x=>x.id!==m.id&&x.photo_id===p.id))await removePhoto(get(),p);fresh()},error);
 q('[data-to-expense]').onclick=()=>{const r=result();if(!r||r.totals.KRW<=0){error('請先勾選並確認菜色與價格');return}const items=draft.items.filter(x=>x.selected);onExpenseDraft({title:draft.title||'本餐',date:draft.date,currency:'KRW',amount:String(r.totals.KRW),notes:items.map(x=>`${x.translated_name||x.original_name} ${x.spec||''} ×${x.quantity}`).join('；'),split:'equal'})};
 function render(s){snapshot=s;const selected=q('[data-saved]').value;q('[data-saved]').innerHTML='<option value="">選擇已保存菜單</option>'+s.menus.map(m=>`<option value="${esc(m.id)}">${esc(m.date)} · ${esc(m.title)}</option>`).join('');q('[data-saved]').value=selected;const updated=s.menus.find(m=>m.id===draft.id);if(updated&&draft.version&&updated.version!==draft.version){if(dirty)q('[data-menu-status]').textContent='另一位訪客已更新此試算，請按載入核對最新內容；目前未儲存內容仍保留。';else{draft=structuredClone(updated);draw();q('[data-menu-status]').textContent='共用試算已更新';}}result();}
 function setDraft(value){draft={id:crypto.randomUUID(),date:koreaDay(),title:'本餐試算',items:[],budget:null,photo_id:null,...structuredClone(value)};dirty=true;draw()}
 draw();return {render,setDraft,getDraft:()=>structuredClone(draft)};
}
