export function validatePhoto({type,size}){if(!['image/jpeg','image/png','image/webp'].includes(type))throw Error('請使用 JPEG、PNG 或 WebP；HEIC 可先截圖');if(!Number.isFinite(size)||size<=0||size>8388608)throw Error('圖片不可超過 8 MB');return true}
export function translationBatch(items){if(items.length>100)throw Error('菜單最多辨識 100 項，請分區拍攝');const q=items.map(x=>[x.original_name,x.spec].filter(Boolean).join(' '));if(q.join('').length>10000)throw Error('菜單文字超過 10,000 字，請分區拍攝');return q}
function linesFrom(input){if(typeof input==='string')return input.split(/\n/).map(x=>x.trim()).filter(Boolean);const a=input?.textAnnotations;if(!a?.length)return String(input?.fullTextAnnotation?.text||'').split(/\n/).filter(Boolean);
 const words=a.slice(1).map(w=>{const v=w.boundingPoly?.vertices||[];return {text:w.description||'',x:Math.min(...v.map(v=>v.x||0)),y:Math.min(...v.map(v=>v.y||0)),h:Math.max(...v.map(v=>v.y||0))-Math.min(...v.map(v=>v.y||0))}}).filter(w=>w.text);if(!words.length)return a[0].description.split('\n').filter(Boolean);
 const rows=[];for(const w of words.sort((a,b)=>a.y-b.y||a.x-b.x)){let row=rows.find(r=>Math.abs(r.y-w.y)<=Math.max(6,w.h*.55));if(!row){row={y:w.y,words:[]};rows.push(row)}row.words.push(w)}return rows.sort((a,b)=>a.y-b.y).map(r=>r.words.sort((a,b)=>a.x-b.x).map(w=>w.text).join(' '));}
const pricePattern=()=>/(?:₩\s*)?(\d{1,3}(?:,\d{3})+|\d{3,8})(?:\s*원)?(?![\d.,A-Za-z%])(?!\s*(?:g|kg|ml|인분|그램|그람)\b)/gi;
export function parseReceipt(input){const lines=linesFrom(input),text=lines.join('\n');let candidates=[];for(const line of lines){if(/카드번호|card\s*(no|number)|거스름|change|부가세|tax|받은|tender/i.test(line))continue;if(!/합\s*계|총\s*액|결제\s*금액|total|결제액/i.test(line))continue;for(const m of line.matchAll(pricePattern())){const amount=Number(m[1].replaceAll(',',''));if(amount>0&&amount<100000000)candidates.push({amount,label:line})}}
 candidates=candidates.filter((c,i,a)=>a.findIndex(x=>x.amount===c.amount)===i);const match=text.match(/(20\d{2})[.\-/년\s]+(\d{1,2})[.\-/월\s]+(\d{1,2})/);let date=null;if(match){const x=`${match[1]}-${match[2].padStart(2,'0')}-${match[3].padStart(2,'0')}`;if(!isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x)date=x}return {merchant:lines.find(x=>!/^\d|영수증|receipt/i.test(x))||'',date,amountCandidates:candidates,text,uncertain:candidates.length!==1};}
export function parseMenu(input){const lines=linesFrom(input),items=[];for(const line of lines){if(/^(메뉴|menu|가격|price)\s*$/i.test(line)||/^\d+$/.test(line))continue;const matches=[...line.matchAll(pricePattern())];let start=0;if(matches.length){for(const m of matches){const name=line.slice(start,m.index).trim().replace(/[-:.·]+$/,'').trim();start=m.index+m[0].length;if(!name)continue;const price=Number(m[1].replaceAll(',',''));items.push({id:`item-${items.length+1}`,original_name:name,translated_name:'',spec:'',price_minor:price>0?price:null,confirmed:false,quantity:1,selected:false})}const tail=line.slice(start).trim();if(tail&&/[가-힣A-Za-z]/.test(tail)&&tail!=='원')items.push({id:`item-${items.length+1}`,original_name:tail,translated_name:'',spec:'',price_minor:null,confirmed:false,quantity:1,selected:false})}else if(/[가-힣A-Za-z]/.test(line))items.push({id:`item-${items.length+1}`,original_name:line,translated_name:'',spec:'',price_minor:null,confirmed:false,quantity:1,selected:false});}return items.slice(0,100);}
export function photoMagic(bytes){if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)return 'image/jpeg';if(bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47)return 'image/png';if(String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP')return 'image/webp';throw Error('圖片內容不符合支援格式');}
