import {recognizeLocally} from './local-ocr.mjs?v=c2d3fef3332e';
import {updateRow,deleteRow} from './sync.mjs?v=c2d3fef3332e';
export function validatePhoto(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('請使用 JPEG、PNG 或 WebP；HEIC 可先截圖');if(file.size>8388608||file.size<=0)throw Error('圖片不可超過 8 MB');}
export async function preparePhoto(file){validatePhoto(file);let bitmap;try{bitmap=await createImageBitmap(file,{imageOrientation:'from-image'})}catch{throw Error('無法讀取圖片，請改用截圖或 JPG')};const ratio=Math.min(1,2200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*ratio));canvas.height=Math.max(1,Math.round(bitmap.height*ratio));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('圖片處理失敗');validatePhoto(blob);return blob}
export async function uploadPhoto(client,file,kind){const blob=await preparePhoto(file);const id=crypto.randomUUID(),path=`${client.tripId}/${id}.jpg`;const {error}=await client.storage.from('busan-photos').upload(path,blob,{contentType:'image/jpeg',upsert:false});if(error)throw Error(error.message);try{await updateRow(client,'receipt_uploads',id,{path,kind,status:'draft'},null)}catch(e){await client.storage.from('busan-photos').remove([path]);throw e}return {id,path,kind,status:'draft',version:1,blob}}
export async function photoUrl(client,photo){const {data,error}=await client.storage.from('busan-photos').createSignedUrl(photo.path,3600);if(error)throw Error(error.message);return data.signedUrl}
export async function recognizePhoto(client,{photoId,mode,blob,onProgress}){
 if(!blob){const url=await photoUrl(client,{path:`${client.tripId}/${photoId}.jpg`});const response=await fetch(url);if(!response.ok)throw Error('無法讀取照片，請重新連線後再試');blob=await response.blob()}
 return recognizeLocally(blob,mode,onProgress);
}
export async function removePhoto(client,photo){const {error}=await client.storage.from('busan-photos').remove([photo.path]);if(error)throw Error('照片清理失敗，請重試：'+error.message);await deleteRow(client,'receipt_uploads',photo)}
