
(() => {
'use strict';
const trip=window.TRIP, $=id=>document.getElementById(id);
const iconNames={flight:'plane',move:'suitcase',spot:'capsule',food:'food',coffee:'coffee',stay:'suitcase'};
const sticker=name=>`<svg class="sticker-icon" aria-hidden="true"><use href="assets/stickers.svg#${name}"></use></svg>`;
const dayPhotos=[['capsule.jpg','海邊膠囊實景','海邊膠囊 · 17:30 入場','capsule'],['coffee.jpg','全浦咖啡街街區氛圍','咖啡街氛圍參考 · 非指定店家','coffee'],['cable.jpg','松島海上纜車實景','松島海上纜車 · 使用 Busan Pass','cable'],['temple.jpg','海東龍宮寺實景','海東龍宮寺 · 記得留回程時間','suitcase']];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,label,cls='')=>`<a class="${cls}" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`;
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
async function copyAddress(address){try{await navigator.clipboard.writeText(address);toast('地址已複製')}catch{toast('無法自動複製，請長按畫面上的韓文地址複製')}}
function renderDay(index){const d=trip.days[index],photo=dayPhotos[index];document.querySelectorAll('.day-tab').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1});$('day-panel').setAttribute('aria-labelledby',`tab-${index}`);$('day-summary').innerHTML=`<figure class="polaroid day-photo"><span class="paper-tape" aria-hidden="true"></span><img src="assets/${photo[0]}" alt="${escape(photo[1])}" width="900" height="600" loading="lazy"><figcaption>${escape(photo[2])}</figcaption><span class="photo-corner-sticker">${sticker(photo[3])}</span></figure><p class="day-number">0${index+1}</p><h3>${escape(d.name)}</h3><p class="area">${escape(d.area)}</p><p class="intro">${escape(d.intro)}</p><div class="day-note"><strong>這天的小提醒</strong>${escape(d.note)}</div>`;$('day-panel').innerHTML=`<ol class="timeline">${d.items.map(([time,title,detail,type,url,badge,address,extraLinks])=>`<li class="event"><span class="event-time">${escape(time)}</span><span class="event-dot" aria-hidden="true">${sticker(iconNames[type]||'capsule')}</span><article class="event-card"><div class="event-heading"><h3>${escape(title)}</h3>${badge?`<span class="badge">${escape(badge)}</span>`:''}</div><p>${escape(detail)}</p>${address?`<p class="event-address">${escape(address)}</p>`:''}${url||address?`<div class="event-links">${url?link(url,type==='flight'?'查看航班動態':title==='豚笑 / 飯店旁醬蟹'?'醬蟹地圖':'開啟 Naver 地圖'):''}${extraLinks?extraLinks.map(([href,label])=>link(href,label)).join(''):''}${address?`<button class="text-button copy-address" data-address="${escape(address)}">複製地址 ↗</button>`:''}</div>`:''}</article></li>`).join('')}</ol>`;$('day-panel').querySelectorAll('.copy-address').forEach(b=>b.addEventListener('click',()=>copyAddress(b.dataset.address)));window.dispatchEvent(new CustomEvent('busan-day',{detail:index}))}
$('day-tabs').innerHTML=trip.days.map((d,i)=>`<button class="day-tab" role="tab" id="tab-${i}" aria-controls="day-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}"><span class="tab-sticker">${sticker(dayPhotos[i][3])}</span><span class="tab-date">${d.date}<small>${d.week}</small></span><p>DAY 0${i+1}</p></button>`).join('');
const tabs=[...document.querySelectorAll('.day-tab')];tabs.forEach((b,i)=>{b.addEventListener('click',()=>renderDay(i));b.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%4;if(e.key==='ArrowLeft')next=(i+3)%4;if(e.key==='Home')next=0;if(e.key==='End')next=3;if(next!==undefined){e.preventDefault();renderDay(next);tabs[next].focus()}})});
renderDay(0);
$('tips-grid').innerHTML=trip.tips.map(t=>`<article class="tip"><div class="tip-type">${escape(t.type)}</div><h3>${escape(t.title)}</h3><p>${escape(t.text)}</p>${t.url?link(t.url,t.source,'source-link'):`<span class="source-link">${escape(t.source)}</span>`}</article>`).join('');
$('coffee-grid').innerHTML=trip.cafes.map(c=>`<article class="coffee-card"><div class="coffee-icon" aria-hidden="true">${sticker('coffee')}</div><div><p class="coffee-tag">${escape(c.tag)}</p><h3>${escape(c.name)}</h3><p class="branch">${escape(c.branch)}</p><p>${escape(c.text)}</p><p class="address">${escape(c.address)}</p><div class="coffee-actions">${link(c.url,c.source,'source-link')}<button class="text-button copy-address" data-address="${escape(c.address)}">複製地址 ↗</button></div></div></article>`).join('');
$('coffee-grid').querySelectorAll('.copy-address').forEach(b=>b.addEventListener('click',()=>copyAddress(b.dataset.address)));
$('hotel-address').textContent=trip.hotel;$('copy-hotel').addEventListener('click',()=>copyAddress(trip.hotel));
let checks={};try{const saved=JSON.parse(localStorage.getItem('busan-2026-checks')||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))checks=saved}catch{}
function progress(){const done=[...$('checklist').querySelectorAll('input')].filter(i=>i.checked).length;$('check-progress').textContent=`${done} / ${trip.checklist.length} 已準備`}
function saveChecks(values){try{localStorage.setItem('busan-2026-checks',JSON.stringify(values))}catch{toast('目前無法保存，勾選僅保留到這次頁面關閉')}}
$('checklist').innerHTML=trip.checklist.map((v,i)=>`<label class="check-item"><input type="checkbox" data-index="${i}" ${checks[i]===true?'checked':''}><span>${escape(v)}</span></label>`).join('');
$('checklist').querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{checks[input.dataset.index]=input.checked;saveChecks(checks);progress()}));progress();
})();

